name: Daily Fashion News

on:
  schedule:
    # Multiple schedules to improve reliability
    - cron: '16 21 * * *'  # 21:16 UTC
    - cron: '17 21 * * *'  # 21:17 UTC (backup)
    - cron: '18 21 * * *'  # 21:18 UTC (backup)
  workflow_dispatch:  # Allows manual trigger
  repository_dispatch:  # Allows external triggers

jobs:
  send-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Debug information
      run: |
        echo "Workflow triggered at: $(date)"
        echo "GitHub Event: ${{ github.event_name }}"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref }}"
        echo "Actor: ${{ github.actor }}"
        
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Send news to Telegram channel
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: |
        echo "Starting news sending at: $(date)"
        python daily_news_sender.py
        echo "News sending completed at: $(date)" 