name: Daily Fashion News

on:
  schedule:
    # Runs daily at 21:00 UTC
    - cron: '0 21 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  send-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Send news to Telegram channel
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: |
        python daily_news_sender.py 