name: Daily Fashion News

on:
  schedule:
    # Multiple times per day to increase reliability
    - cron: '0 21 * * *'  # 21:00 UTC (main time)
    - cron: '30 21 * * *' # 21:30 UTC (backup)
    - cron: '0 22 * * *'  # 22:00 UTC (backup)
  workflow_dispatch:  # Allows manual trigger
  repository_dispatch:  # Allows external triggers

jobs:
  send-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test workflow
      run: echo "Workflow is running at $(date)"
      
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Send news to Telegram channel
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: |
        python daily_news_sender.py 